sudo: required
dist: bionic

language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get -y update -qq
  - sudo apt-get -y install libdbus-1-dev libnfnetlink-dev libmnl-dev libnetfilter-queue-dev

script: make
