sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get -y update -qq
  - sudo apt-get -y install libdbus-1-dev libnfnetlink-dev libmnl-dev libnetfilter-queue-dev

#  - mkdir -p $HOME/build
#  - cd $HOME/build
#  - git clone git://git.netfilter.org/libnetfilter_queue
#  - cd $HOME/build/libnetfilter_queue
#  - ./autogen.sh
#  - ./configure --prefix=/usr
#  - sudo make install

script: make

