#!/bin/sh -e

. /usr/share/debconf/confmodule

if test "$1" = "configure"; then
    ENABLED=0

    mkdir -p /var/lib/nfblock

    test -f /etc/default/nfblock && . /etc/default/nfblock

    if [ "$ENABLED" = "0" ]; then
        db_stop
        exit 0
    fi

    db_get 'nfblock/download-blocklist' || true

    if [ "$RET" = "true" ]; then
        echo "Downloading, please wait..."
        /etc/cron.daily/nfblock
        /etc/cron.weekly/nfblock
        echo "Downloading complete."
    fi

fi

#DEBHELPER#

db_stop
exit 0
