#!/bin/sh

set -e

. /usr/share/debconf/confmodule

do_configure() {
    ENABLED=0

    mkdir -p /var/lib/nfblock

    test -f /etc/default/nfblock && . /etc/default/nfblock

    if [ "$ENABLED" = "0" ]; then
        db_stop
        return
    fi

    db_get 'nfblock/download-blocklist' || true

    if [ "$RET" = "true" ]; then
        echo "Downloading, please wait..."
        /etc/cron.daily/nfblock
        /etc/cron.weekly/nfblock
        echo "Downloading complete."
    fi
}


if test "$1" = "configure"; then
    do_configure
fi

db_stop

#DEBHELPER#

exit 0
